### ISSUE TITLE
how to load curl-easy without composer autoload

### ISSUE THREAD

**Issue by wozzup** [stil/curl-easy#15]
the composer autoload is use too much memories
request sort by XHProf Incl.MemUse(bytes), as you see the top 10 memories usage list composer use too much.
```
main()
spl_autoload_call
???_op
Composer\Autoload\ClassLoader::loadClass
Composer\Autoload\includeFile
cURL\RequestsQueue::send
cURL\RequestsQueue::socketPerform
spl_autoload_call@1
ComposerAutoloaderInit3163d95abb499df82cfeb181810bb3d1::getLoader
Composer\Autoload\ClassLoader::loadClass@1
Composer\Autoload\includeFile@1
cURL\RequestsQueue::read
```

how to load curl-easy without composer autoload?

**Comment by stil** [comment]
Create custom autoloader:
http://php.net/manual/en/function.spl-autoload-register.php
```php
$curlEasySrcDir = __DIR__.'/../src';

spl_autoload_register(function ($class) use ($curlEasySrcDir) {
    $classPath = $curlEasySrcDir.'/'.strtr($class, '\\', '/').'.php';
    require $classPath;
});
```
You would need to add similiar autoloader for `Symfony/Component/EventDispatcher` library, which is required by curl-easy.

**Comment by wozzup** [comment]
Woooow~ spl-autoloader getting more better memory usage, thanks Mr.stil.
have a nice Valentine's Day
