### ISSUE TITLE
Performance Non-blocking parallel 

### ISSUE THREAD

**Issue by wozzup** [stil/curl-easy#19]
hi Mr.Stil,

it's the `Non-blocking requests in parallel` compare to others methods `Non-blocking requests in parallel`  is more fast and better performance?
https://github.com/stil/curl-easy#non-blocking-requests-in-parallel

**Comment by stil** [comment]
The performance is the same, but in "non-blocking" method you can do something else while requests are processed. And if you use blocking method, the script just hangs until processed requests are complete.
