### ISSUE TITLE
Set up a queue, add during lifetime of script

### ISSUE THREAD

**Issue by twinsit** [stil/curl-easy#23]
I am busy with creating a server that reads info from mqtt and needs to process it (post it to another url). Therefor I found this script.
What I need to do is set up the curl-easy queue, and when I have on MQTT a new message, there should be added a requests.

What I Tried now is on starting of the MQTT handler:
```
$queue = new \cURL\RequestsQueue;
$queue
    ->getDefaultOptions()
    ->set(CURLOPT_RETURNTRANSFER, true);
```

Then every time there is a new requests I add it like this
`$req = new \cURL\Request('<url>');
    $req->getOptions()->set(CURLOPT_POSTFIELDS, $data);
    $requests[] = $req;
`

And after every message I call 
`$queue->attach(array_pop($requests));
$queue->send();`

But is that the correct way? Because now I think that the queue is executed multiple times.

In fact the final result should be:
- set up queue
- on new message: add request
- on new message: add request
...

and that in the background the requests are done (with a maximum nr of requests at a certain time would be very nice).

Thanks

**Comment by stil** [comment]
If you need to process multiple requests but with upper limit of requests in queue at once, I suggest you to look at [stil/curl-robot](https://github.com/stil/curl-robot).
