### ISSUE TITLE
Codificacion charset error

### ISSUE THREAD

**Issue by diegogonda** [stil/curl-easy#24]
Hello, 
Using curl-easy to download json data from a restfull service, the charset was encoded in another type different of my petition (UTF-8), and this is a huge problem because I need to use the accent marks (like á, é, í, ó, ú, etc.).
Could your library solve this problem?
Reggards!

**Comment by stil** [comment]
The JSON format safely escapes UTF-8 byte sequences. It means that cURL is engaged in encoding and decoding plain ASCII bytes. Your problem is not related to curl-easy so I'm closing it.
