### ISSUE TITLE
Getting request class not found error

### ISSUE THREAD

**Issue by arpitx165** [stil/curl-easy#27]
I have tried to include this library using composer but still i am getting class not found error Can any one tell me how can i fix this one

for including library i used :-  require_once 'vendor/autoload.php';

**Comment by stil** [comment]
Paste the output of `composer install` execution. You're probably getting some errors while installation.

**Comment by arpitx165** [comment]
@still : this is my composer.json  file

 {
    "require": {
        "stil/curl-easy": "*"
    }
}

After running this command :   php composer.phar install
Output :
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/event-dispatcher (v2.8.7)
    Downloading: 100%         

  - Installing stil/curl-easy (v1.1.4)
    Downloading: 100%         

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Writing lock file
Generating autoload files
