### ISSUE TITLE
Reuse same Connection

### ISSUE THREAD

**Issue by kremsy** [stil/curl-easy#31]
Is there any way to use the lib as such it does not kill active keep-alive connections, so that it sends multiple requests over the same connection?

**Comment by stil** [comment]
Are you sure it does kill connections after single use?
Can you show the log with `CURLOPT_VERBOSE` option enabled?

If you use easy (single request at once, blocking) interface it will close connection unless you reuse the handle with [curl_reset](https://secure.php.net/manual/en/function.curl-reset.php).

If you use multi interface, connections should be shared between requests as long as you have your multi handle open.

**Comment by kremsy** [comment]
We tried a lot, up to now we did not come to a solution, we use the multi interface, reusing the handle but it always opening a new connection, we are currently trying to investigate, we will keep uptodate here.

**Comment by kremsy** [comment]
Shortly made a verbose dump, have to leave now, investigate next days further:

`* Hostname was NOT found in DNS cache
*   Trying 91.121.211.8...
* Connected to dedimania.net (91.121.211.8) port 8081 (#0)
> POST /Dedimania HTTP/1.1
User-Agent: ManiaControl v0.219
Host: dedimania.net:8081
Accept: */*
Accept-Encoding: deflate, gzip
Content-Type: text/xml; charset=UTF-8;
Keep-Alive: timeout=600, max=2000
Connection: Keep-Alive
Content-Encoding: gz1ip
Content-Length: 457

* upload completely sent off: 457 out of 457 bytes
< HTTP/1.1 400 Bad Request
< Date: Sat, 20 May 2017 16:45:09 GMT
* Server Dedimania.8081 is not blacklisted
< Server: Dedimania.8081
< Accept-Ranges: bytes
< Content-Length: 131
< Keep-Alive: timeout=600, max=2000
< Connection: Keep-Alive
< Content-Type: text/xml; charset=UTF-8
< Accept-Encoding: deflate, gzip
< Content-Encoding: deflate
< Set-Cookie: PHPSESSID=74ccd1c0972ecbc1968161ad0a7d08e2; path=/
< 
* Connection #0 to host dedimania.net left intact
`

**Comment by stil** [comment]
I tried this code sample
```php
<?php
require __DIR__ . '/vendor/autoload.php';

// We will check current Bitcoin price via API.
$queue = new \cURL\RequestsQueue();
$queue->getDefaultOptions()
    ->set(CURLOPT_TIMEOUT, 5)
    ->set(CURLOPT_VERBOSE, true);

$once = false;

$queue->addListener('complete', function (\cURL\Event $event) use (&$once) {
    if (!$once) {
        $request = new \cURL\Request('https://bitpay.com/rates/EUR');
        $event->queue->attach($request);
        $once = true;
    }
});


$request = new \cURL\Request('https://bitpay.com/rates/USD');
// Add request to queue
$queue->attach($request);

$queue->send();
```

And it looks like it's reusing connections:
```
*   Trying 104.20.80.236...
* Connected to bitpay.com (104.20.80.236) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
* 	 subject: jurisdictionC=US; jurisdictionST=Delaware; businessCategory=Private Organization; serialNumber=5163966; C=US; ST=Georgia; L=Atlanta; O=BitPay, Inc.; CN=bitpay.com
* 	 start date: Mar 23 18:22:00 2017 GMT
* 	 expire date: Apr 25 19:11:00 2019 GMT
* 	 subjectAltName: bitpay.com matched
* 	 issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
* 	 SSL certificate verify ok.
> GET /rates/USD HTTP/1.1
Host: bitpay.com
Accept: */*

< HTTP/1.1 200 OK
< Date: Sat, 20 May 2017 22:40:51 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 54
< Connection: keep-alive
< Set-Cookie: __cfduid=d8aed255f3091e933731e25a4dd9349b81495320051; expires=Sun, 20-May-18 22:40:51 GMT; path=/; domain=.bitpay.com; HttpOnly
< Strict-Transport-Security: max-age=31536000
< X-Download-Options: noopen
< X-Content-Type-Options: nosniff
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD,GET,POST,PUT,DELETE,OPTIONS
< Access-Control-Allow-Headers: Content-Type,Authorization,Content-Length,X-Requested-With,Cache-Control,X-Accept-Version,x-signature,x-pubkey,x-identity,cf-connecting-ip
< Cache-Control: public, max-age=60, s-maxage=60
< Expires: Sat, 20 May 2017 22:40:56 GMT
< ETag: W/"36-ba0b0752"
< CF-Cache-Status: HIT
< Server: cloudflare-nginx
< CF-RAY: 3622ccd09c866b13-WAW
< 
{"data":{"code":"USD","name":"US Dollar","rate":1996}}* Connection #0 to host bitpay.com left intact
* Found bundle for host bitpay.com: 0x55ae4d2db060 [can pipeline]
* Re-using existing connection! (#0) with host bitpay.com
* Connected to bitpay.com (104.20.80.236) port 443 (#0)
> GET /rates/EUR HTTP/1.1
Host: bitpay.com
Accept: */*

< HTTP/1.1 200 OK
< Date: Sat, 20 May 2017 22:40:51 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 64
< Connection: keep-alive
< Set-Cookie: __cfduid=d8aed255f3091e933731e25a4dd9349b81495320051; expires=Sun, 20-May-18 22:40:51 GMT; path=/; domain=.bitpay.com; HttpOnly
< Strict-Transport-Security: max-age=31536000
< X-Download-Options: noopen
< X-Content-Type-Options: nosniff
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD,GET,POST,PUT,DELETE,OPTIONS
< Access-Control-Allow-Headers: Content-Type,Authorization,Content-Length,X-Requested-With,Cache-Control,X-Accept-Version,x-signature,x-pubkey,x-identity,cf-connecting-ip
< Cache-Control: public, max-age=60, s-maxage=60
< Expires: Sat, 20 May 2017 22:40:57 GMT
< ETag: W/"40-fc085007"
< CF-Cache-Status: HIT
< Server: cloudflare-nginx
< CF-RAY: 3622ccd10cb46b13-WAW
< 
{"data":{"code":"EUR","name":"Eurozone Euro","rate":1780.87112}}* Connection #0 to host bitpay.com left intact
```

**Comment by kremsy** [comment]
Thanks for the tests, after some debugging (@Bueddl) found out that the problem actually was in our implementation, we had a own Queue instead of using the Requests queue so it killed the multi_connection

https://github.com/ManiaControl/ManiaControl/commit/2ec6fdbed9510e2d999d0fcb77ad72c6ca267911#diff-4e3d9f6baee865d5fdb9783b298b6654
