### ISSUE TITLE
[Help] Different cookies in parallel

### ISSUE THREAD

**Issue by jLynx** [stil/curl-easy#35]
Is there a way to send 2 requests to the same url in parallel, but on one request a cookie is set to "Cookie: user=1" and on the 2nd request it's set to "Cookie: user=2" for example?

Thanks!

**Comment by stil** [comment]
Sure, just

```php
$request1->getOptions()->set(CURLOPT_COOKIE, 'user=1');
$request2->getOptions()->set(CURLOPT_COOKIE, 'user=2);
```

then attach requests to queue with
```php
$queue->attach($request1);
$queue->attach($request2);
```
