### ISSUE TITLE
No error code is displayed

### ISSUE THREAD

**Issue by zhex900** [stil/curl-easy#37]
Hi,
I am having trouble getting error code and message. `$response->getError();` returns null.

    public function curl_req($path, $data = array())
          {
             $request = new \cURL\Request($this->_url . $path);
            $request->getOptions()
              ->set(CURLOPT_TIMEOUT, 5)
              ->set(CURLOPT_RETURNTRANSFER, true)
              ->set(CURLOPT_HEADER,true)
              ->set(CURLOPT_VERBOSE,true)
               ->set(CURLINFO_HEADER_OUT,true)
              ->set(CURLOPT_USERAGENT,'curl/7.54.0')
              ->set(CURLOPT_HTTPHEADER, $this->getHeader());
            if( !empty($data) ) {
               $request->getOptions()
                   ->set(CURLOPT_POSTFIELDS, json_encode($data))
                   ->set(CURLOPT_SAFE_UPLOAD, true);
            }
            if ($response->hasError()) {
                $error = $response->getError();
                $e = 'Error code: ' . $error->getCode() . 'Message: "' . $error->getMessage() . '"' . "\n";
            }
         
            $this->getLogger()->info('Connect to server: '.$e. ' try: '.$try);
        
        $feed = json_decode($response->getContent(), true);

        return $feed;
    }

curl verbose:
< HTTP/1.1 401 Unauthorized
< Server: nginx/1.10.0 (Ubuntu)
< Content-Type: application/json
< Transfer-Encoding: chunked
< Cache-Control: no-cache
< WWW-Authenticate: WSSE realm="Secured API", profile="UsernameToken"
< Date: Tue, 12 Sep 2017 12:09:56 GMT
< Set-Cookie: SERVERID=web1; path=/
< 
* Connection #0 to host orocampus.tk left intact
NULL

**Comment by stil** [comment]
It's expected behaviour.
`getError()` would return something, if there was network connection problems, DNS problems or for example timeout problem.

You have received full HTTP response. Either it's `200 OK`, or `401 Authorized` it doesn't matter. cURL library has successfully delivered your request to destination server and returned you a response to the request.

**Comment by zhex900** [comment]
Okay. Thank you!.
